set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  add_compile_options(-Wall -Wextra -Wpedantic -Werror)
  if(CMAKE_BUILD_TYPE MATCHES "Debug")
    append("--coverage" CMAKE_CXX_FLAGS)
  endif()
else()
  add_compile_options(-Wall -Wextra -Wpedantic -Werror)
  add_link_options(-fuse-ld=lld)
  if(CMAKE_BUILD_TYPE MATCHES "Debug")
    append("-fprofile-instr-generate -fcoverage-mapping" CMAKE_CXX_FLAGS)
  endif()
endif()

if(NOT (CMAKE_BUILD_TYPE MATCHES "Debug"))
  append("-flto" CMAKE_CXX_FLAGS)
endif()
